apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler
metadata:
  name: resource-consumer-memory 
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: resource-consumer 
  minReplicas: 1 
  maxReplicas: 10 
  metrics: 
  - type: Resource
    resource:
      name: memory 
      target:
        type: AverageValue 
        averageValue: 500Mi 
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60