apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: memory-autoscale 
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment
    name: resource-consumer
  minReplicas: 1 
  maxReplicas: 10 
  metrics: 
  - type: Resource
    resource:
      name: memory 
      target:
        type: Utilization 
        averageUtilization: 70 
  behavior: 
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 120
      selectPolicy: Max
    scaleDown: 
      policies: 
      - type: Pods 
        value: 1 
        periodSeconds: 60
      selectPolicy: Min 
      stabilizationWindowSeconds: 60
