apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: resource-consumer
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment
    name: resource-consumer
  targetCPUUtilizationPercentage: 800
